# axlap/config/elasticsearch/elasticsearch.yml
cluster.name: "axlap-es-cluster"
node.name: "axlap-es-node1"
network.host: 0.0.0.0
http.port: 9200

xpack.security.enabled: false

# Performance settings - consider adjusting based on available system resources
# These are often set via ES_JAVA_OPTS in docker-compose.yml for heap,
# but other settings like caches can be put here.
# indices.memory.index_buffer_size: 10% # Default is 10% of total heap
# indices.queries.cache.size: 10% # Default is 10% of total heap

# Slow query logging - useful for identifying performance bottlenecks
index.search.slowlog.threshold.query.info: 5s
# index.search.slowlog.threshold.query.warn: 10s
# index.search.slowlog.threshold.query.debug: 2s
# index.search.slowlog.threshold.fetch.info: 1s
# index.indexing.slowlog.threshold.index.info: 5s
