# axlap/config/filebeat/filebeat.yml
filebeat.inputs:
- type: log # Changed from 'docker' or 'container' to 'log' for specific file paths
  enabled: true
  paths:
    - /var/log/zeek_json/*.log # Zeek JSON logs (conn.log, http.log, etc.)
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: message # If Zeek logs are pure JSON objects per line
  tags: ["zeek"]
  processors:
    - add_fields:
        target: event
        fields:
          kind: "zeek_log" # To help differentiate in Elasticsearch

- type: log
  enabled: true
  paths:
    - /var/log/suricata/eve.json # Suricata EVE JSON logs
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: message # EVE JSON is one JSON object per line
  tags: ["suricata"]
  processors:
    - add_fields:
        target: event
        fields:
          kind: "suricata_event" # To help differentiate
    - if:  # Extract rule name and severity for easier querying
        contains:
          json.event_type: "alert"
      then:
        - rename:
            fields:
              - from: "json.alert.signature"
                to: "rule.name"
              - from: "json.alert.severity"
                to: "rule.severity"
              - from: "json.alert.category"
                to: "rule.category"
        - script:
            lang: javascript
            source: >
              function process(event) {
                var alert = event.Get("json.alert");
                if (alert && alert.gid && alert.signature_id && alert.rev) {
                  event.Put("rule.id", alert.gid + ":" + alert.signature_id + ":" + alert.rev);
                }
              }
    - if:
        contains:
          json.event_type: "flow"
      then:
        - add_fields:
            target: event
            fields:
              kind: "suricata_flow"

- type: log # For AXLAP custom Zeek logs
  enabled: true
  paths:
    - /var/log/zeek_json/axlap_*.log # Match custom logs like axlap_http_detailed.log
  json.keys_under_root: true
  json.add_error_key: true
  json.message_key: message
  tags: ["zeek", "axlap_custom"] # Tag for custom logs
  processors:
    - add_fields:
        target: event
        fields:
          kind: "zeek_custom_log"

# General Filebeat settings
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false

# Output to Elasticsearch
output.elasticsearch:
  hosts: ["axlap-elasticsearch:9200"]
  protocol: "http"
  # index: "filebeat-%{[agent.version]}-%{+yyyy.MM.dd}" # Default index pattern
  # Custom index based on tags or fields:
  indices:
    - index: "axlap-zeek-%{+yyyy.MM.dd}"
      when.contains:
        tags: "zeek"
    - index: "axlap-suricata-%{+yyyy.MM.dd}"
      when.contains:
        tags: "suricata"
  # Consider setting up an ILM policy in Elasticsearch and referencing it here
  # for better index lifecycle management (e.g., rollover, deletion).
  # ilm.enabled: true
  # ilm.policy_name: "axlap-filebeat-policy"
  # ilm.rollover_alias: "axlap-zeek"
  # ilm.pattern: "{now/d}-000001"

  # Template for custom mappings and settings (optional but recommended for production)
  # setup.template.name: "axlap-filebeat"
  # setup.template.pattern: "axlap-*"
  # setup.template.overwrite: true
  # setup.template.settings:
  #   index.number_of_shards: 1 # For single node ES cluster
  #   index.codec: best_compression # For saving space, trades some indexing speed

# Logging
logging.level: info
logging.to_files: true
logging.files:
  path: /usr/share/filebeat/logs
  name: filebeat
  keepfiles: 7
  permissions: 0644
